package com.infostretch.nest.providers;

public interface ESSEndPoints {

	public final static String GET_BASIC_DETAILS = "/get-basic-details";
	public final static String GET_PERSONAL_DETAILS = "/get-personal-details";
	public final static String GET_BASE_LOCATION = "/get-base-location";
	public final static String GET_IDENTITY_DATAILS ="/get-identity-details";
	public final static String GET_RR_COUNT ="/get-RR-count";
	public final static String GET_PRIVILEGES_LIST="/get-privileges-list";
	public final static String GET_EMPLOYEE_GOALS_HOBBIES="/get-employee-goals-hobbies";
	public final static String EDIT_EMPLOYEE_GOALS="/edit-Employee-Goals";
	public final static String EDIT_EMPLOYEE_HOBBIES="/edit-Employee-Hobbies";
	public final static String GET_COUNTRY_NAME="/get-country-name";
	public final static String GET_EMEGENCY_CONTACT_DETAILS="/get-emergency-contact-details";
	public final static String GET_FAMILY_MEMEBERS="/get-family-members";
	public final static String GET_EMPLOYEE_RELATIONSSHIP_DETAILS="/get-employee-relationship-details";
	public final static String GET_ROLE_TITLE="/get-role-title";
	public final static String GET_EMPLOYEE_LOCAION_PRIVILEDGES="/get-employee-location-privileges";
	public final static String SAVE_LOCATION_PRIVILEDGE="/save-location-privileges";
	public final static String SAVE_PRIVILEDGES="/save-privileges";
	public final static String EMPLOYEE_PRIVILEGES = "/get-employee-privileges";
	public final static String CONTACT_DETAILS = "/get-contact-details";
	public final static String EMPLOYEE_LANGUAGES = "/get-employee-languages";
	public final static String PROFESSIONAL_EXPERIANCE = "/get-professional-exp";
	public final static String EDIT_PROFESSIONAL_EXPERIANCE = "/edit-professional-exp";
	public final static String DELETE_PROFESSIONAL_EXPERIANCE = "/delete-professional-exp";
	public final static String EDUCATION_LEVEL = "/get-education-level";
	public final static String LANGUAGE_NAME = "/get-language-name";
	public final static String QUALIFICATION_DETAILS = "/get-qualification-details";
	public final static String REPORTING_STRUCTURE = "/get-reporting-structure";
	public final static String COMPETENCY = "/get-competency";
	public final static String FLUENCY = "/get-fluency";
	public final static String BGV_STATUS = "/bgv-status";
	public final static String MARITAL_STATUS = "/get-marital-status";
	public final static String EMPLOYEE_STATUS = "/get-employee-status";
	public final static String RELATIONSHIP_DATA = "/get-relationship-data";
	public final static String EDIT_RELATIONSHIP_DATA = "/edit-relationship-data";
	public final static String DELETE_RELATIONSHIP_DATA = "/delete-relationship-data";
	public final static String EDIT_BASIC_DETAILS = "/edit-basic-details";
	public final static String EDIT_PERSONAL_DETAILS = "/edit-personal-details";
	public final static String EDIT_IDENTITY_DETAILS = "/edit-identity-details";
	public final static String EDIT_EMERGENCY_CONTACT_DETAILS = "/edit-emergency-contact-details";
	public final static String DELETE_EMERGENCY_CONTACT_DETAILS = "/delete-emergency-contact-details";
	public final static String EDIT_FAMILY_MEMBERS = "/edit-family-members";
	public final static String DELETE_FAMILY_MEMBERS = "/delete-family-members";
	public final static String GET_ROLE_DESCRIPTION = "/get-role-description";
	public final static String EDIT_ROLE_DESCRIPTION ="/edit-role-description";
	public final static String UPLOAD_DISPLAY_PIC ="/upload-display-pic";
	public final static String DELETE_DISPLAY_PIC ="/delete-display-pic";
	public final static String GET_NATIONALITY ="/get-nationality";
	public final static String GET_BUSINESS_UNIT ="/get-business-unit";
}
